version: '3'
services:
  blockchain:
    build: .
    # ports:
    # - "8081:8081"
    depends_on:
    - redis
    environment:
    - REDIS_ENDPOINT=redis
    - REDIS_PORT=6379

  redis:
    image: 'bitnami/redis:5.0'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
    - '6379:6379'
    volumes:
    - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
